-- DELECAO DAS TABELAS ATUAIS

DROP TABLE RELATORIO
DROP TABLE PERMISSOES_USUARIOS
DROP TABLE TELAS_PERMISSOES
DROP TABLE USUARIOS
DROP TABLE FORNECEDORES
DROP TABLE CADASTROS_GERAIS
DROP TABLE RESERVA
DROP TABLE MERCADO
DROP TABLE PLAN_ITENS
DROP TABLE DATAS
DROP TABLE PLAN_COLECIONAVEIS
DROP TABLE PLAN_CABECALHO
DROP TABLE PDFS
DROP TABLE LICENCIANTES


