'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PlanejamentoCadastro

    '''<summary>
    '''hdnCodPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCodPlan As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnEdicao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnEdicao As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnValidaTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnValidaTab As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TabContainer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabContainer1 As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tab1 As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''pnlEtapa1Outros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEtapa1Outros As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPDFS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPDFS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCodPanini control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodPanini As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlEtapa1CodColec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEtapa1CodColec As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtPDFSAlbum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDFSAlbum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCodAlbum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodAlbum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDFSEnv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDFSEnv As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCodEnv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodEnv As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDescPDFS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescPDFS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkAssinatura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAssinatura As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblDescDivisao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescDivisao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblColecao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblColecao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''drpCategoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpCategoria As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblDescTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescTipo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''drpPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpPeriod As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeriod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAno As Global.Panini.NumberBox

    '''<summary>
    '''lblDtLancto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDtLancto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDtLancto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDtLancto As Global.Panini.DateBox

    '''<summary>
    '''pnlEdicoes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEdicoes As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtJan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJan As Global.Panini.NumberBox

    '''<summary>
    '''txtFev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFev As Global.Panini.NumberBox

    '''<summary>
    '''txtMar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMar As Global.Panini.NumberBox

    '''<summary>
    '''txtAbr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAbr As Global.Panini.NumberBox

    '''<summary>
    '''txtMai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMai As Global.Panini.NumberBox

    '''<summary>
    '''txtJun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJun As Global.Panini.NumberBox

    '''<summary>
    '''txtJul control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJul As Global.Panini.NumberBox

    '''<summary>
    '''txtAgo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAgo As Global.Panini.NumberBox

    '''<summary>
    '''txtSet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSet As Global.Panini.NumberBox

    '''<summary>
    '''txtOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOut As Global.Panini.NumberBox

    '''<summary>
    '''txtNov control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNov As Global.Panini.NumberBox

    '''<summary>
    '''txtDez control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDez As Global.Panini.NumberBox

    '''<summary>
    '''btnLimpar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLimpar1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnProximo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnProximo1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tab2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tab2 As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''txtArquivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArquivo As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnCarregar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCarregar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''imgUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgUpload As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''hdnImgUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnImgUpload As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlOcultarCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOcultarCol As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblFormato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormato As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFormato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFormato As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPreco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPreco As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPreco1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPreco1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblValReais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValReais As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtQtdePag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdePag As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCustoEditorialP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustoEditorialP As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCustoEditTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustoEditTotal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQtdeCapa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdeCapa As Global.Panini.NumberBox

    '''<summary>
    '''txtQtdeMiolo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdeMiolo As Global.Panini.NumberBox

    '''<summary>
    '''txtCapa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCapa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMiolo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMiolo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlEtapa2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEtapa2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtCromo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCromo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEnvelope control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnvelope As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPrecoCromo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrecoCromo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPrecoEnvelope control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrecoEnvelope As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQtdTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdTotal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQtdCN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdCN As Global.Panini.NumberBox

    '''<summary>
    '''txtQtdCE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdCE As Global.Panini.NumberBox

    '''<summary>
    '''txtCromoEnv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCromoEnv As Global.Panini.NumberBox

    '''<summary>
    '''txtEnvPacote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnvPacote As Global.Panini.NumberBox

    '''<summary>
    '''txtEnvCaixa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnvCaixa As Global.Panini.NumberBox

    '''<summary>
    '''txtQtdeAlbumPacote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdeAlbumPacote As Global.Panini.NumberBox

    '''<summary>
    '''btnLimpar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLimpar2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnVoltar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVoltar2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnProximo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnProximo2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tab3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tab3 As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''rdSim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdSim As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdNao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdNao As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtBrinde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBrinde As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTipoServico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTipoServico As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAcabamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAcabamento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''drpDistr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpDistr As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''drpFase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpFase As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtBinding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBinding As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtManuseio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManuseio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''drpFornecedor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpFornecedor As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlEtapa3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEtapa3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rdItalia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdItalia As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdBrasil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdBrasil As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdOutros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdOutros As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtCustoEditorial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustoEditorial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdSimMerc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdSimMerc As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdNaoMerc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdNaoMerc As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtPais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPais As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFormatoCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFormatoCol As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQtdPagCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdPagCol As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPapelCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPapelCol As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCortesiaCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCortesiaCol As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMioloCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMioloCol As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdSimCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdSimCol As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdNaoCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdNaoCol As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdSimEsp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdSimEsp As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdNaoEsp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdNaoEsp As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdSimPoster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdSimPoster As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdNaoPoster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdNaoPoster As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''btnLimpar3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLimpar3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnVoltar3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVoltar3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSalvar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalvar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlMensagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMensagem As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''oMensagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents oMensagem As Global.Panini.Mensagem

    '''<summary>
    '''dvFocus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvFocus As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
